SELECT 
    C.CAR_ID, 
    C.CAR_TYPE, 
    CAST(C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100) AS SIGNED) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
  ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단','SUV')
  AND P.DURATION_TYPE = '30일 이상'
  AND C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100) BETWEEN 500000 AND 1999999
  AND C.CAR_ID NOT IN (
      SELECT H.CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
      WHERE NOT (H.END_DATE < '2022-11-01' OR H.START_DATE > '2022-11-30')
  )
ORDER BY 
    FEE DESC,
    C.CAR_TYPE ASC,
    C.CAR_ID DESC;
