-- 코드를 입력하세요
SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE as P
JOIN REST_REVIEW as R
ON P.MEMBER_ID=R.MEMBER_ID
WHERE R.MEMBER_ID=(
    SELECT R2.MEMBER_ID
FROM REST_REVIEW as R2
GROUP BY R2.MEMBER_ID
ORDER BY COUNT(*) DESC
LIMIT 1
)
ORDER BY REVIEW_DATE ASC,
R.REVIEW_TEXT ASC